# Generated by Django 4.0.1 on 2022-03-21 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=127)),
                ('nazwisko', models.CharField(max_length=127)),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('data_smierci', models.DateField(blank=True, null=True)),
                ('zdiecie', models.CharField(blank=True, help_text='Wpisz link do zdięcia', max_length=255, null=True)),
                ('zyciorys', models.TextField(blank=True, max_length=2047, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Wpisz gatunek książki', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=127)),
                ('opis', models.TextField(blank=True, help_text='Wpisz krótki opis książki', max_length=4095)),
                ('isbn', models.CharField(help_text='<a href="https://www.isbn-international.org">Numer ISBN</a>', max_length=13, verbose_name='ISBN')),
                ('obraz', models.CharField(blank=True, help_text='Wpisz link do obrazu', max_length=255, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.autor')),
                ('gatunek', models.ManyToManyField(help_text='Wybierz gatunek książki', to='catalog.Gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='Egzemplarz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalny ID dla konkretnego egzemplarza książki', primary_key=True, serialize=False)),
                ('wydawca', models.CharField(max_length=127)),
                ('zwrot', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('k', 'Konserwacja'), ('w', 'Wypożyczona'), ('d', 'Dostępna'), ('z', 'Zarezerwowana')], default='k', help_text='Dostępność książki', max_length=1)),
                ('ksiazka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ksiazka')),
                ('odbiorca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['zwrot'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
    ]
